name: Bun CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: cd dev && bun install --frozen-lockfile && bun run build
      - run: bun install --frozen-lockfile
      - run: bun test
