name: Bun CI

on:
  pull_request:
    types: [opened, closed]
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: cd dev && bun install --frozen-lockfile && bun run build && bun link
      - run: cd project && bun install --frozen-lockfile && bun link bun-chrome-extension-dev
      - run: bun install --frozen-lockfile
      - run: bun test
