name: Bun CI

on:
  pull_request:
    types: [opened, closed]
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: cd project && bun install
      - run: bun install --frozen-lockfile
      - run: bun test
