name: Bun CI

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: cd config && bun link
      - run: cd project && bun link ../config --save
      - run: bun install --frozen-lockfile
      - run: bun test
