name: Create dev package and upload to GitHub

on:
  push:
    branches: master
    paths: ["dev/**", ".github/workflows/create-dev-package.yaml"]

defaults:
  run:
    working-directory: dev

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build package
        run: bun run build

      - name: Create package
        run: bun pm pack

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: dev
          path: dev/bun-chrome-extension-dev-*.tgz
          if-no-files-found: error
          overwrite: true
