name: Publish bce package to npm registry

on:
  workflow_dispatch:
    inputs:
      version:
        description: "What version part do you want to change?"
        required: true
        type: choice
        default: "patch"
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Create version-bce branch
        run: git checkout -b version-bce

      - name: Bump version
        uses: phips28/gh-action-bump-version@v11.0.7
        with:
          version-type: ${{ inputs.version }}
          skip-tag: true
          commit-message: "Bump ${{ inputs.version }} version of bce"
          bump-policy: "ignore"
          target-branch: "version-bce"

      - name: PR to main
        run: gh pr create -B master -H version-bce -t "Bump version" -b "New version" --no-maintainer-edit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR
        run: gh pr merge version-bce -d -m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
