name: Publish dev package to npm registry

on:
  workflow_dispatch:
    inputs:
      version:
        description: "What version part do you want to change?"
        required: true
        type: choice
        default: "patch"
        options:
          - major
          - minor
          - patch

defaults:
  run:
    working-directory: dev

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Create version branch
        run: git checkout -b version

      - name: Bump version
        uses: phips28/gh-action-bump-version@v11.0.7
        with:
          version-type: ${{ inputs.version }}
          skip-tag: true
          commit-message: "Bump ${{ inputs.version }} version of dev"
          bump-policy: "ignore"
        env:
          PACKAGEJSON_DIR: "dev"

      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: dev

      - name: Log workspace
        run: cd ${{ github.workspace }} && ls -r
