name: Test dev and bce packages

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install and Test dev package
        run: cd dev && bun install --frozen-lockfile && bun test

      - name: Install and Test bce package
        run: bun install --frozen-lockfile && bun test
