name: Check package.json version

on:
  pull_request:
    branches: ["master"]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Get package.json version
        id: check
        uses: EndBug/version-check@v2.1.4
        with:
          diff-search: true
          file-name: dev/package.json

      - name: Check if package.json version changed
        if: steps.check.outputs.changed == 'false'
        run: echo "Version in package.json has not changed"
