name: Check package.json version

on:
  pull_request:
    branches: ["master"]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Check if package.json version is updated
        uses: EndBug/version-check@v2
        id: check
