name: Check package.json version

on:
  pull_request:
    branches: ["master"]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Get updates in dev folder
        id: changes
        run: |
          if [[ $(git diff --name-only origin/master...HEAD | grep dev) ]]; then
            echo "updated=true" >> "$GITHUB_OUTPUT"
          else
            echo "updated=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Check if dev folder updated
        if: steps.changes.outputs.updated == 'false'
        run: exit 0

      - name: Get package.json version
        id: check
        uses: EndBug/version-check@v2.1.4
        with:
          diff-search: true
          file-name: dev/package.json

      - name: Check if package.json version changed
        if: steps.check.outputs.changed == 'false'
        run: |
          echo "Version in package.json has not changed"
          exit 1
